### ISSUE TITLE
Hard coded Ledger timeout is too short

### ISSUE THREAD

**Issue by abrkn** [SpankChain/spankbank-web3#5]
Using a Ledger Nano S, it's not possible to approve the transaction before the 7 second hard coded timeout elapses, in `spankbank.ts`:

```
transport.exchangeTimeout = 7000
```

The default timeout (30 sec) would be sufficient.

**Comment by ameensol** [comment]
@alexanvl please evaluate

**Comment by wolever** [comment]
Thanks for the report, @abrkn!

The reason for the lower timeout was so that we could more quickly detect whether or not a Ledger device is attached.

I've made the timeout configurable, here: https://github.com/SpankChain/spankbank-web3/commit/0a8ac60fcd913441a49466caf9266a0f65ed61b7

And the SpankBank will be updated as soon as this PR is accepted: https://github.com/SpankChain/spankbank-explorer_frontend/pull/3
